name: deploy

on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: Deploy via sFTP
    env:
      SFTP_USER: ${{ secrets.SFTP_USER }}
      SFTP_HOST: ${{ secrets.SFTP_HOST }}
      SFTP_PORT: ${{ secrets.SFTP_PORT }}
      SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
    steps:
      - run: git submodule update --init
      - run: |
        export THEME_NAME=accessible-minimalism-wordpress-theme && \
        lftp --password "$SFTP_PASSWORD" \
          -e "mirror -R theme/$THEME_NAME public_html/wp-contents/theme/$THEME_NAME; bye" \
          "sftp://$SFTP_USER@$SFTP_HOST:$SFTP_PORT"

