name: deploy

on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: Deploy via sFTP
    runs-on: ubuntu-latest
    env:
      SFTP_USER: ${{ secrets.SFTP_USER }}
      SFTP_HOST: ${{ secrets.SFTP_HOST }}
      SFTP_PORT: ${{ secrets.SFTP_PORT }}
      SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install lftp
        run: sudo apt-get install -qy lftp
      - run: git submodule update --init
      - run: mkdir ~/.lftp/
      - run: echo "set ssl:verify-certificate no" >> ~/.lftp/rc
      - run: echo "set sftp:auto-confirm yes" >> ~/.lftp/rc
      - run: export THEME_NAME=accessible-minimalism-wordpress-theme
      - run: lftp --password "$SFTP_PASSWORD" -e "mirror -Rv theme/$THEME_NAME public_html/wp-contents/theme/$THEME_NAME; bye" "sftp://$SFTP_USER@$SFTP_HOST:$SFTP_PORT"

